### PR TITLE
Resolvendo Issue 3

### PR DESCRIPTION
**Pull request by Vitorrecoaro**
<describe the changes you have made here: what, why, ...>

- [x] Change in CHANGELOG.md described
- [x] Tests created for changes
- [x] Screenshots added (for bigger UI changes)

### CODE REVIEW

**Review by Mobuos — COMMENTED** [review]
Parece ótimo @Vitorrecoaro 👍

**Review by Mobuos — APPROVED** [review]

**Review by Thi08 — APPROVED** [review]

**Comment by brunol-pereira** [comment]
Muito Bom @Vitorrecoaro 👍

**Review by brunol-pereira — COMMENTED** [review]
👍

**Comment by Marx-Coxinha** [comment]
Não vi nenhum erro.

Em qua, 21 de set de 2022 16:32, João Dini ***@***.***>
escreveu:

**Pull request merged**
